### ISSUE TITLE
README does not match repo contents

### ISSUE THREAD

**Issue by ssshake** [liflg/unreal.tournament_451-english_x86#1]
This binary is not in the repository but its the main parts of the installation instructions. ut-install-436.run

I'm not sure how to use this repo. I just wish to install UT on ubuntu.

**Comment by and3rson** [comment]
@rettichschnidi Any updates on this? It used to work when liflg.org was up and now this repo does not contain the installer itself nor any README on what to do.

**Comment by and3rson** [comment]
@ssshake I think I've found the files in several other places:

- https://cloud.leboeuf.eu/index.php/s/EWtzCfKLF5JySen
- https://github.com/XenGi/oldgames/tree/master/ut

**Comment by rettichschnidi** [comment]
No, we have no plans to work on this anymore.

Please see https://github.com/liflg/docs for how to create an installer.

**Comment by ssshake** [comment]
@and3rson thanks! I'm building a retro linux box to relive my youth around the late 90's / early 2000's era. Which mean I need gnome 2, enlightenment 16, xmms, and of course UT!
